# ASP.NET Core
- task: AzureCLI@1
  inputs:
- task: AzurePowerShell@4
  inputs:
    ScriptType: 'FilePath'
    scriptLocation: 'scriptPath'
    scriptPath: 
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
